name: build

on:
  push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: setup
      uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.2.4

    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cabal-store
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build packages
      run: cabal build --enable-tests --ghc-options="-Werror"

    - name: Test packages
      run: cabal test
